// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'App': string;
  'Dialog': string;
}
export const cssExports: CssExports;
export default cssExports;
