// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'black': string;
  'cell': string;
  'red': string;
}
export const cssExports: CssExports;
export default cssExports;
